# Generated by Django 2.1.7 on 2019-03-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_remove_feed_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='policy_pubkey',
            field=models.BinaryField(default=b'empty', editable=True),
        ),
    ]
