# Generated by Django 2.1.7 on 2019-03-29 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0003_feed_policy_pubkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feed',
            name='alice_passphrase',
            field=models.CharField(max_length=200),
        ),
    ]
