# Generated by Django 2.1.7 on 2019-03-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20190329_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='policy_pubkey',
            field=models.CharField(default=None, max_length=2000),
        ),
    ]
