# Generated by Django 2.1.7 on 2019-03-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_auto_20190329_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='policy_pubkey',
            field=models.CharField(default='Not Created', max_length=2000),
        ),
    ]
