# Generated by Django 2.1.7 on 2019-03-29 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_auto_20190329_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='alice_passphrase',
        ),
        migrations.RemoveField(
            model_name='post',
            name='label_string',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
    ]
