# Generated by Django 2.1.7 on 2019-03-29 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_auto_20190329_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='enrico_pubkey',
            new_name='enrico_pubkey_hex',
        ),
        migrations.RenameField(
            model_name='feed',
            old_name='policy_pubkey',
            new_name='policy_pubkey_hex',
        ),
    ]
