# Generated by Django 2.1.7 on 2019-03-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_auto_20190329_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='enrico_pubkey_hex',
            field=models.CharField(default='Not Created', max_length=2000),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(default='Not Created', max_length=2000),
        ),
    ]
