# Generated by Django 2.1.7 on 2019-04-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0012_post_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='art_steward_address',
            field=models.CharField(default='0x13a225FB5533bF144F8c484e0E5eD09A6aaDc45c', max_length=2000),
        ),
        migrations.AddField(
            model_name='feed',
            name='erc721_address',
            field=models.CharField(default='0xe5560289be2a80826ea72dB95e0b14379A7C4d3E', max_length=2000),
        ),
    ]
