# Generated by Django 2.1.7 on 2019-04-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_auto_20190404_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='provider',
            field=models.CharField(default='http://127.0.0.1:8545', max_length=2000),
        ),
    ]
